CREATE LOGIN RestrictedUser WITH PASSWORD = '$(RESTRICTED_USER_PASSWORD)';
USE BeanTrade;
CREATE USER RestrictedUser FOR LOGIN RestrictedUser;
GRANT SELECT, INSERT, UPDATE, REFERENCES, EXECUTE ON DATABASE::BeanTrade TO RestrictedUser;