IF OBJECT_ID('dbo.Users','U') IS NOT NULL
    DROP TABLE dbo.Users
GO

CREATE TABLE [Users] (
  [UserID] INT PRIMARY KEY IDENTITY(1, 1),
  [UserGuid] VARCHAR(256) DEFAULT (CONVERT(VARCHAR(256), NEWID())),
  [CreatedAt] DATETIME2 DEFAULT (GETUTCDATE()),
  [LastLoginAt] DATETIME2,
  [IsActive] BIT DEFAULT (1)
)
GO