name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Capture Terraform Outputs
        id: tf_outputs
        run: |
          echo "DB_HOST=$(terraform output -raw db_host)" >> $GITHUB_ENV
          echo "DB_NAME=$(terraform output -raw db_name)" >> $GITHUB_ENV

      - name: Install Flyway
        run: |
          curl -L "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.2.1/flyway-commandline-9.2.1-linux-x64.tar.gz" | tar xz
          export PATH="$(pwd)/flyway-9.2.1:$PATH"

      - name: Run Flyway Migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/migrations:/flyway/sql \
            flyway/flyway \
            -url="jdbc:sqlserver://${{ env.DB_HOST }};databaseName=${{ env.DB_NAME }};encrypt=true;trustServerCertificate=true" \
            -user="${{ secrets.TF_VAR_DB_USERNAME }}" \
            -password="${{ secrets.TF_VAR_DB_PASSWORD }}" \
            migrate